name: ecommerce
 
on: push
 
jobs: 
  buildimg:
    runs-on: self-hosted 
    steps:

    - name: Code Checkout
      uses: actions/checkout@v4.2.2

    - name: DockerLogin
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: buildimg
      run: |
        docker build -t reactappimg:${GITHUB_RUN_NUMBER} .
        docker tag reactappimg:${GITHUB_RUN_NUMBER} frankisinfotech/reactapp:${GITHUB_RUN_NUMBER}
        docker push frankisinfotech/reactapp:${GITHUB_RUN_NUMBER}
