name: ecommerce

on: push

jobs:
  buildimg:
    runs-on: ubuntu-latest
    steps:

    - name: Code Checkout
      uses: actions/checkout@v4.2.2

    - name: DockerLogin
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: buildimg
      run: |
        docker build -t reactappimg:${GITHUB_RUN_NUMBER} .
        docker tag reactappimg:${GITHUB_RUN_NUMBER} frankisinfotech/reactapp:${GITHUB_RUN_NUMBER}
        docker push frankisinfotech/reactapp:${GITHUB_RUN_NUMBER}

  build-and-push-pub-ecr:
    needs: buildimg
    runs-on: ubuntu-latest
    steps:
   
      - name: Login to Public ECR
        uses: docker/login-action@v3
        with: 
          registry: public.ecr.aws
          username: ${{ secrets.ACCESS_KEY }}
          password: ${{ secrets.SECRET_ACCESS_KEY }}
        env:
          aws-region: ${{ secrets.REGION }} 

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build -t react_pub .
          docker tag react_pub:latest public.ecr.aws/o1a4z2b4/react_pub:${GITHUB_RUN_NUMBER}
          docker push public.ecr.aws/o1a4z2b4/react_pub:${GITHUB_RUN_NUMBER}
